### ISSUE TITLE
How to add new posts?

### ISSUE THREAD

**Issue by adix-code** [zzzmisa/hugo-theme-doors#1]
How can i add new posts? I followed exactly the steps posted on README.md.

**Comment by zzzmisa** [comment]
Doors is a single-page Hugo theme. You can’t add a post. Just add your project’s links, your SNS, to config.toml, and you’re set.

**Comment by zzzmisa** [comment]
Doors is a single-page Hugo theme. You can’t add a post. Just add your project links, contact links, to `config.toml`, and you’re set.
